### ISSUE TITLE
Progress Tracking (to first release)

### ISSUE THREAD

**Issue by guyfleeman** [guyfleeman/VaSOLSim#1]
ALPHA 
- [ ] 0.6.0a 
  - [ ] finish student client alpha
    - [x] finish login node
    - [x] implement testing governor
    - [ ] implement exam import
    - [ ] implement question renderers
  - [ ] finish teacher client alpha
    - [x] finish exam export
    - [ ] start and complete exam export for local editable copies (no data is encrypted or hashed)

BETA 
- [ ] 0.7.0b
  - [ ] update question text to use HTML formatting
    - [ ] write webview initializer
    - [ ] change text field question initializers to HTML editors (note in JavaFX this is actually a text editor with font and color options that exports text as html. The user doesn't actually have to write any tags)
    - [ ] change question labels to webviews
      - [ ] style the webview
  - [ ] add CDATA support (for tags and images) to the exam export/import class
- [ ] 0.8.0b
  - [ ] add image support to answer choices in teacher client
    - [ ] the answer choice initialization nodes need to be updates to accept images
    - [ ] the answer choice initialization nodes need to properly scale images, so the full res image is not sitting in memory
    - [ ] update the exam export class to support images in answer choices
  - [ ] add image support to answer choice in student client
    - [ ] add image support to question renderers to support image in answer choices
    - [ ] update the exam import class to handle images for answer choices
- [ ] 0.9.0b
  - [ ] revise the current stats form
    - [ ] remove sender email, password, smtp addr, and smtp port (google has a public webserver for sending emails without authorizing an account)
    - [ ] keep stats destination email
  - [ ] add question difficulty to Question class
    - [ ] add functionality to exam import/export class
    - [ ] add difficulty dropdown to question creation nodes
  - [ ] add statistics reporting
    - [ ] decide on an email "encoding" for statistics
    - [ ] implement a statistics gathering system on the student client
    - [ ] implement a statistics sending system on the student client that will send emails to the destination account using the above mentioned google service
    - [ ] implement a statistics gathering system on the teacher client using javamail via IMAP
    - [ ] implement a statistics tree below the exam view tree
    - [ ] implement nodes to view and manipulate statistics on the teacher client

BETA TESTING
- [ ] test teacher client
  - [ ] Windows
  - [ ] Mac
  - [ ] Debian
- [ ] test student client
  - [ ] Windows
  - [ ] Mac
  - [ ] Debian

FIRST RELEASE
- [ ] ensure gradle compiles dependencies and binaries cross-platform with no addition work other than a git clone and a gradle build command sequence
- [ ] compile binaries
- [ ] github binary release
