### ISSUE TITLE
Getting out of Alpha

### ISSUE THREAD

**Issue by guyfleeman** [guyfleeman/VaSOLSim#10]
Getting out alpha most involves mostly student client work, nonetheless, here is the todo list. Most of this is in the master checklist, but a few things have been expanded upon.
- [ ] finish student client alpha
  - [x] finish login node
  - [ ] write test UI (see #6)
    - [ ] resource viewer
    - [ ] navigation bar
    - [ ] question display (interface with #2)
  - [x] implement testing governor (see #3)
  - [ ] implement exam import (see #9)
  - [ ] implement question renderers (see #2)
- [ ] finish teacher client alpha
  - [ ] finish exam export (see #9)
  - [ ] start and complete exam export for local editable copies (no data is encrypted or hashed)
